version: "3"

services:
  dev-environment:
    image: composable-logs-dev
    volumes:
    - ./workspace:/home/host_user/workspace
    ports:
    - "8888:8888"
    environment:
    - "CC_OPENTELEMETRY_OTLP_COLLECTOR_ENDPOINT=http://otel-collector:4317"
    command:
    - |
      cd /home/host_user/workspace

      pip3 install --user --editable ./composable_logs/.

      jupyter notebook --no-browser --port 8888 --ip 0.0.0.0
    hostname: composable-logs-dev
