FROM pynb-dag-runner

USER root
RUN apt-get install -y -q entr
USER host_user

# Jupyter server is only run in dev-mode
ARG JUPYTER_TOKEN
ENV JUPYTER_TOKEN=$JUPYTER_TOKEN

# See
# https://docs.python.org/3/using/cmdline.html#environment-variables
# ENV PYTHONDEVMODE="1"
