# See, https://github.com/tmuxinator/tmuxinator

name: watch_tests
root: .

tmux_options: -f .tmux.conf

startup_window: watch_tests

windows:
  - watch_tests:
      layout: main-vertical
      panes:
        - make watch-test-pytest
        - make watch-test-mypy
        - make watch-test-black
