name: "CI/CD: Publish snapshot package to PyPI"

on:
  workflow_dispatch:

  push:
    branches:
      - gha-ci-refactor  # debug trigger
      - main

permissions:
  contents: none

jobs:
  ci--test-code-and-build-python-pacakge:
    uses: ./.github/workflows/ci/_run-tests-and-build-python-package.yml
    with:
      python-package-release-target: snapshot-release

  cd--push-wheel-to-pypi:
    needs: ci--test-code-and-build-python-pacakge
    uses: ./.github/workflows/cicd/_push_wheel_to_pypi.yml
    with:
      python-package-release-target: snapshot-release
    secrets:
      PYPI_SECRET_TOKEN: ${{ secrets.PYPI_SECRET_TOKEN }}
