version: "3"

vars:
  DOCKER_IMAGE: ci-tools-image

tasks:
  build:
    desc: Build project Docker image
    vars:
      HOST_UID: {sh: "id -u"}
      HOST_GID: {sh: "id -g"}
    cmds:
      - |
        docker build \
          --file docker/Dockerfile.base \
          --build-arg HOST_UID={{.HOST_UID}} \
          --build-arg HOST_GID={{.HOST_GID}} \
          --tag {{.DOCKER_IMAGE}} \
          .

  # ----
  # It seems that the "interactive" setting in Taskfile can not be set dynamically.
  # Therefore we define two (internal) tasks as below.
  #
  # See:
  #   https://taskfile.dev/#/usage?id=interactive-cli-application
  #
  # Since these tasks have no descriptions, the do not show up in "task --list"
  run-interactive-true:
    cmds:
      - |
        {{if eq .IS_INTERACTIVE "true"}}
          {{.COMMAND}}
        {{else}}
          : skipped
        {{end}}
    interactive: true

  run-interactive-false:
    cmds:
      - |
        {{if eq .IS_INTERACTIVE "false"}}
          {{.COMMAND}}
        {{else}}
          : skipped
        {{end}}
    interactive: false

  run:
    desc: Run bash command in project Docker image (interactive if IS_INTERACTIVE=true)
    # Eg.
    #   task docker:run -- "ls -al ."
    #   task docker:run -- "(printenv; pip3 freeze)"
    vars:
      # if IS_INTERACTIVE is not set, assume false
      IS_INTERACTIVE: '{{if eq .IS_INTERACTIVE "true"}}true{{else}}false{{end}}'
      INTERACTIVE_SWITCH: '{{if eq .IS_INTERACTIVE "true"}}-i{{else}}{{end}}'
      COMMAND: |
        docker run --rm -t \
          {{.INTERACTIVE_SWITCH}} \
          --network none \
          --volume {{.PWD}}/workspace:/home/host_user/workspace \
          --workdir /home/host_user/workspace/ \
          {{.DOCKER_IMAGE}} \
          "{{.CLI_ARGS}}"

    cmds:
      - task: run-interactive-false
        vars:
          COMMAND: "{{.COMMAND}}"
          IS_INTERACTIVE: "{{.IS_INTERACTIVE}}"
      - task: run-interactive-true
        vars:
          COMMAND: "{{.COMMAND}}"
          IS_INTERACTIVE: "{{.IS_INTERACTIVE}}"

  shell:
    desc: Start an interactive shell in project Docker image
    cmds:
      - task: run
        vars:
          IS_INTERACTIVE: "true"
          CLI_ARGS: '/bin/bash' # this is not ideal, we are running "bash -c /bin/bash"
