# See, https://github.com/tmuxinator/tmuxinator

name: watch_tests
root: ~/workspace/

tmux_options: -f .tmux.conf

startup_window: watch_tests

windows:
  - watch_tests:
      layout: main-vertical
      panes:
        - make pytest WATCH_MODE=1
        - make mypy WATCH_MODE=1
        - make black WATCH_MODE=1
