version: "3"

vars:
  WATCH_MODE: '{{.WATCH_MODE}}'
  WATCH_COMMAND: '{{if eq .WATCH_MODE "true"}}find . | grep ".py" | entr{{else}}{{end}}'

tasks:
  pytest:
    desc: Run unit tests (pytest)
    cmds:
      - '{{.WATCH_COMMAND}} bash -c "(date; pytest -vvv tests)"'

  mypy:
    desc: Check static mypy type checks (mypy)
    cmds:
      - "{{.WATCH_COMMAND}} mypy static_builder tests"

  black:
    desc: Check that code is Black formatted (black)
    cmds:
      - "{{.WATCH_COMMAND}} black --check --diff ."

  watch-all:
    desc: Watch unit tests, mypy static tests and black formatting (in tmux session)
    # exit with Ctrl-B + "kill-session"
    cmds:
      - "tmuxinator start"
