site_name: composable-logs
site_url: https://composable-logs.github.io/composable-logs/

markdown_extensions:
  # --- below from ---
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # --- below from ---
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # --- needed for image caption ---
  # See: https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html

  # --- below from ---
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # --- below from ---
  # https://squidfunk.github.io/mkdocs-material/reference/lists/#configuration
  - pymdownx.tasklist:
     custom_checkbox: true

  # --- below based on ---
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration
  - admonition

  # The mkdocs-material repo (https://github.com/squidfunk/mkdocs-material)
  # is MIT licensed.
  # ---

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    #- navigation.indexes

  icon:
    # Github logo for showing repo stats, see repo_-keys below
    repo: fontawesome/brands/github

    # top left site logo
    #logo: material/fast-forward-outline
    #logo: material/fast-forward
    #logo: material/dots-circle
    #logo: fontawesome/solid/circle-nodes
    #logo: fontawesome/solid/angles-right
    #logo: fontawesome/solid/angle-right
    #logo: material/play-box-outline
    logo: material/chevron-right-box-outline
  # ---
  # To find icons:
  #   - select "Icon, bundled" under "Logo" section in below link;
  #   - click on "+" to open the icon search.
  #
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#__tabbed_1_2
  #

repo_url: https://github.com/composable-logs/composable-logs
repo_name: composable-logs

# Disable "Edit" button linking to Github, see
# https://www.mkdocs.org/user-guide/configuration/
edit_uri: ""

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'home/index.md'
#
# The nav feature is rather briefly documentated:
#   https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
#
# For more advanced features, see relation between nav-field
# in mkdocs-material homepage
#
#   https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
#
# versus actual page
#
#   https://squidfunk.github.io/mkdocs-material/
#
nav:
  - Home:
     - Intro:
        - "What is pynb-dag-runner?": home/index.md
        - Notebook support: home/notebook-support.md
        - Similar projects: home/similar-projects.md
     - Development:
        - Key repositories: dev/index.md
        - Local dev setup: dev/local-dev.md
        - Local UI dev setup: dev/local-ui-dev.md
        - OpenTelemetry schema: dev/opentelemetry-span-format.md
  - Demo:
        - Overview: live-demos/mnist-digits-demo-pipeline/index.md
        - Screeshots: live-demos/mnist-digits-demo-pipeline/screenshots.md
        - Cloning the demo pipeline: live-demos/mnist-digits-demo-pipeline/cloning-the-demo.md

  - Roadmap: roadmap/index.md
  - Contact: contact/index.md
