site_name: pynb-dag-runner

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand

    - navigation.indexes

  # Github logo for showing repo stats, see repo_-keys below
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/pynb-dag-runner/pynb-dag-runner
repo_name: pynb-dag-runner


#
# The nav feature is rather briefly documentated:
#   https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
#
# For more advanced features, see relation between nav-field
# in mkdocs-material homepage
#
#   https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
#
# versus actual page
#
#   https://squidfunk.github.io/mkdocs-material/
#
nav:
  - Home:
    - Welcome: home/index.md
    - Contributions: home/contributions.md
    - Contact: contact/index.md
  - Live demos:
    - mnist-digits-demo-pipeline: live-demos/mnist-digits-demo-pipeline.md
  - Next steps: next-steps/index.md
  - OpenTelemetry schema:
    - OpenTelemetry schema: ref/spans.md
  - Contact: contact/index.md
