name: "Automated tests"

on:
  workflow_call:


defaults:
  run:
    shell: bash
    working-directory: .  # repo root

# Note: the below does not test code under otel_output_parser

jobs:
  run-all-tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Build docker image"
        run: |
          make docker-build-all

      - name: "Run unit tests"
        run: |
          make \
              RUN_ENVIRONMENT="${{ env.RUN_ENVIRONMENT }}" \
              COMMAND="(cd pynb_dag_runner; make test-pytest )" \
              docker-run-in-cicd

      - name: "Run mypy type checks"
        run: |
          make \
              COMMAND="(cd pynb_dag_runner; make test-mypy )" \
              docker-run-in-cicd

      - name: "Check black formatting"
        run: |
          make \
              COMMAND="(cd pynb_dag_runner; make test-black )" \
              docker-run-in-cicd

      - name: "Build Python wheel-file for the pynb-dag-runner library"
        run: |
          make \
              COMMAND="(cd pynb_dag_runner; make clean build )" \
              docker-run-in-cicd

      - name: "Store wheel-file as build artefact"
        uses: actions/upload-artifact@v2
        with:
          name: pynb-dag-runner-wheel
          path: ${{ github.workspace }}/workspace/pynb_dag_runner/dist/
          if-no-files-found: error
          retention-days: 5
