name: "ci: test PR commits"

# On commits to PR:s into main branch (except for files listed below)
#  - Run automated tests + check that package builds
#  - Persist package as Github artifact for short-term debugging

on:
  # See:
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - LICENSE.md
      - README.md

  workflow_dispatch:

jobs:
  ci-run-tests-on-new-commit:
    permissions:
      contents: none

    uses: ./.github/workflows/_ci-run-tests-and-build-python-package.yml
    with:
      python-package-release-target: ci-build
