name: "ci/cd: publish snapshot package to PyPI"

on:
  workflow_dispatch:

  push:
    branches:
      - gha-ci-refactor  # debug trigger
      - main

permissions:
  contents: none

jobs:
  ci-test-code-and-build-python-pacakge:
    uses: ./.github/workflows/_ci-run-tests-and-build-python-package.yml
    with:
      python-package-release-target: snapshot-release

  cd-upload-wheel-to-pypi:
    needs: ci__test-code-and-build-python-pacakge
    uses: ./.github/workflows/_cd-upload-wheel-to-pypi.yml
    with:
      python-package-release-target: snapshot-release
    secrets:
      PYPI_SECRET_TOKEN: ${{ secrets.PYPI_SECRET_TOKEN }}
