name: "Security scan"

on:
  #push:
  #  branches:
  #    - development
  #  paths-ignore:
  #    - "**/*.md"

  #pull_request:
  #  types: [opened, synchronize, reopened]
  #  branches:
  #    - development
  #  paths-ignore:
  #    - "**/*.md"

  # Run every 4:20 UTC, Mondays
  schedule:
    - cron: "20 4 * * 1"

  workflow_dispatch:

permissions:
  contents: none
  security-events: write

jobs:
  run-trivy-docker-scans:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build docker images
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          make build-docker-images

      # ------
      # The below following instructions from here:
      #
      #  https://github.com/aquasecurity/trivy-action
      #
      # Note that we build three docker images, but one scan the last one
      # since each image is built based on the previous one.
      #
      # Trivy (and the below Trivy action) are Apache 2 licensed.

      - name: "Trivy: Scan 'pynb-dag-runner-dev' Docker image"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pynb-dag-runner-dev
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif

      - name: "upload all Trivy scan results to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif

      # ------
